// <auto-generated />
using DryRidgeProgramming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DryRidgeProgramming.Migrations
{
    [DbContext(typeof(DryRidgeProgrammingContext))]
    [Migration("20220125135520_InitialCreateA")]
    partial class InitialCreateA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DryRidgeProgramming.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("NumberOfOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionAA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionAC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID");

                    b.ToTable("Question");
                });
#pragma warning restore 612, 618
        }
    }
}
